/* Generated By:JJTree&JavaCC: Do not edit this line. EG1Constants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int REAL = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int LIST = 9;
  /** RegularExpression Id. */
  int STR = 10;
  /** RegularExpression Id. */
  int CARACT = 11;
  /** RegularExpression Id. */
  int SE = 12;
  /** RegularExpression Id. */
  int SENAO = 13;
  /** RegularExpression Id. */
  int SENAOSE = 14;
  /** RegularExpression Id. */
  int ENQUANTO = 15;
  /** RegularExpression Id. */
  int PARA = 16;
  /** RegularExpression Id. */
  int VERDADEIRO = 17;
  /** RegularExpression Id. */
  int FALSO = 18;
  /** RegularExpression Id. */
  int IMPRIMIR = 19;
  /** RegularExpression Id. */
  int MAIS = 20;
  /** RegularExpression Id. */
  int MENOS = 21;
  /** RegularExpression Id. */
  int MULTIPLICAR = 22;
  /** RegularExpression Id. */
  int DIVIDIR = 23;
  /** RegularExpression Id. */
  int ATRIBUICAO = 24;
  /** RegularExpression Id. */
  int MAIOR = 25;
  /** RegularExpression Id. */
  int MENOR = 26;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 27;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 28;
  /** RegularExpression Id. */
  int IGUAL = 29;
  /** RegularExpression Id. */
  int DIFERENTE = 30;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 31;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 32;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 33;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 34;
  /** RegularExpression Id. */
  int ABRE_COLCHETE = 35;
  /** RegularExpression Id. */
  int FECHA_COLCHETE = 36;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 37;
  /** RegularExpression Id. */
  int VIRGULA = 38;
  /** RegularExpression Id. */
  int PONTO = 39;
  /** RegularExpression Id. */
  int CONSTANTE_INT = 40;
  /** RegularExpression Id. */
  int CONSTANTE_REAL = 41;
  /** RegularExpression Id. */
  int DIGITO = 42;
  /** RegularExpression Id. */
  int VARIAVEL = 43;
  /** RegularExpression Id. */
  int CARACTERE = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"INT\"",
    "\"REAL\"",
    "\"BOOL\"",
    "\"LIST\"",
    "\"STR\"",
    "\"CARACT\"",
    "\"SE\"",
    "\"SENAO\"",
    "\"SENAOSE\"",
    "\"ENQUANTO\"",
    "\"PARA\"",
    "\"VERDADEIRO\"",
    "\"FALSO\"",
    "\"IMPRIMIR\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\" >=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<CONSTANTE_INT>",
    "<CONSTANTE_REAL>",
    "<DIGITO>",
    "<VARIAVEL>",
    "<CARACTERE>",
  };

}
