/* Generated By:JavaCC: Do not edit this line. EG1TreeConstants.java Version 5.0 */
package javacc;

public interface EG1TreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTFIMDOARQUIVO = 1;
  public int JJTOP_REL = 2;
  public int JJTCONST_TIPO = 3;
  public int JJTOP_ARIT = 4;
  public int JJTVARIAVEL = 5;
  public int JJTNUMERO = 6;
  public int JJTNUMVAR = 7;
  public int JJTOPERACAO = 8;
  public int JJTOPNUMVAR = 9;
  public int JJTATOPNUMVAR = 10;
  public int JJTRELACAO = 11;
  public int JJTATRIBUICAO = 12;
  public int JJTDECLARACAO = 13;
  public int JJTCONTEUDOCOND = 14;
  public int JJTCONTEUDOBLOCO = 15;
  public int JJTBLOCO = 16;
  public int JJTCONDICIONAL = 17;
  public int JJTREPETICAO = 18;


  public String[] jjtNodeName = {
    "programa",
    "fimDoArquivo",
    "op_rel",
    "const_tipo",
    "op_arit",
    "variavel",
    "numero",
    "numVar",
    "operacao",
    "opNumVar",
    "atOpNumVar",
    "relacao",
    "atribuicao",
    "declaracao",
    "conteudoCond",
    "conteudoBloco",
    "bloco",
    "condicional",
    "repeticao",
  };
}
/* JavaCC - OriginalChecksum=d40de1da1989f8f502ae309b67a61cb2 (do not edit this line) */
